-- MySQL Script generated by MySQL Workbench
-- Sat Mar 21 09:15:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema roskilde_daycare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema roskilde_daycare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `roskilde_daycare` DEFAULT CHARACTER SET utf8 ;
USE `roskilde_daycare` ;

-- -----------------------------------------------------
-- Table `roskilde_daycare`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roskilde_daycare`.`group` ;

CREATE TABLE IF NOT EXISTS `roskilde_daycare`.`group` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `avg_age` DECIMAL(2,1) NOT NULL,
  PRIMARY KEY (`group_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roskilde_daycare`.`parent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roskilde_daycare`.`parent` ;

CREATE TABLE IF NOT EXISTS `roskilde_daycare`.`parent` (
  `parent_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `birth_date` DATE NOT NULL,
  `sex` VARCHAR(1) NULL,
  PRIMARY KEY (`parent_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roskilde_daycare`.`child`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roskilde_daycare`.`child` ;

CREATE TABLE IF NOT EXISTS `roskilde_daycare`.`child` (
  `child_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `birth_date` DATE NOT NULL,
  `sex` VARCHAR(1) NULL,
  `age` INT NOT NULL,
  `joined_date` DATE NULL,
  `group_id` INT NOT NULL,
  `parent_id` INT NOT NULL,
  PRIMARY KEY (`child_id`),
  INDEX `fk_child_group1_idx` (`group_id` ASC) VISIBLE,
  INDEX `fk_child_parent1_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_child_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `roskilde_daycare`.`group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_child_parent1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `roskilde_daycare`.`parent` (`parent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roskilde_daycare`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roskilde_daycare`.`teacher` ;

CREATE TABLE IF NOT EXISTS `roskilde_daycare`.`teacher` (
  `teacher_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `birth_date` DATE NOT NULL,
  `sex` VARCHAR(1) NULL,
  `salary` INT NOT NULL,
  `group_id` INT NOT NULL,
  `super_id` INT NOT NULL,
  PRIMARY KEY (`teacher_id`),
  INDEX `fk_teacher_group1_idx` (`group_id` ASC) VISIBLE,
  INDEX `fk_teacher_teacher1_idx` (`super_id` ASC) VISIBLE,
  CONSTRAINT `fk_teacher_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `roskilde_daycare`.`group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teacher_teacher1`
    FOREIGN KEY (`super_id`)
    REFERENCES `roskilde_daycare`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roskilde_daycare`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roskilde_daycare`.`schedule` ;

CREATE TABLE IF NOT EXISTS `roskilde_daycare`.`schedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `#_activities` INT NOT NULL,
  `nap_hrs_daily` INT NOT NULL,
  `activity_hrs_weekly` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `fk_schedule_group1_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `roskilde_daycare`.`group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roskilde_daycare`.`appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roskilde_daycare`.`appointment` ;

CREATE TABLE IF NOT EXISTS `roskilde_daycare`.`appointment` (
  `appointment_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `time` INT NOT NULL,
  `child_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  PRIMARY KEY (`appointment_id`),
  INDEX `fk_appointment_child1_idx` (`child_id` ASC) VISIBLE,
  INDEX `fk_appointment_teacher1_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_appointment_child1`
    FOREIGN KEY (`child_id`)
    REFERENCES `roskilde_daycare`.`child` (`child_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `roskilde_daycare`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roskilde_daycare`.`waiting_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roskilde_daycare`.`waiting_list` ;

CREATE TABLE IF NOT EXISTS `roskilde_daycare`.`waiting_list` (
  `entry_id` INT NOT NULL AUTO_INCREMENT,
  `date_added` DATE NOT NULL,
  `reason` VARCHAR(500) NOT NULL,
  `child_id` INT NOT NULL,
  PRIMARY KEY (`entry_id`),
  INDEX `fk_waiting_list_child1_idx` (`child_id` ASC) VISIBLE,
  CONSTRAINT `fk_waiting_list_child1`
    FOREIGN KEY (`child_id`)
    REFERENCES `roskilde_daycare`.`child` (`child_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roskilde_daycare`.`activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roskilde_daycare`.`activity` ;

CREATE TABLE IF NOT EXISTS `roskilde_daycare`.`activity` (
  `activity_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`activity_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roskilde_daycare`.`telephone_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roskilde_daycare`.`telephone_list` ;

CREATE TABLE IF NOT EXISTS `roskilde_daycare`.`telephone_list` (
  `phone_number` VARCHAR(8) NOT NULL,
  `parent_id` INT NOT NULL,
  PRIMARY KEY (`phone_number`, `parent_id`),
  CONSTRAINT `parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `roskilde_daycare`.`parent` (`parent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roskilde_daycare`.`schedule_has_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roskilde_daycare`.`schedule_has_activity` ;

CREATE TABLE IF NOT EXISTS `roskilde_daycare`.`schedule_has_activity` (
  `schedule_schedule_id` INT NOT NULL,
  `activity_activity_id` INT NOT NULL,
  `#_instances` INT NOT NULL,
  PRIMARY KEY (`schedule_schedule_id`, `activity_activity_id`),
  INDEX `fk_schedule_has_activity_activity1_idx` (`activity_activity_id` ASC) VISIBLE,
  INDEX `fk_schedule_has_activity_schedule1_idx` (`schedule_schedule_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_has_activity_schedule1`
    FOREIGN KEY (`schedule_schedule_id`)
    REFERENCES `roskilde_daycare`.`schedule` (`schedule_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_has_activity_activity1`
    FOREIGN KEY (`activity_activity_id`)
    REFERENCES `roskilde_daycare`.`activity` (`activity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roskilde_daycare`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roskilde_daycare`.`user` ;

CREATE TABLE IF NOT EXISTS `roskilde_daycare`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `teacher_id` INT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE,
  INDEX `fk_user_teacher1_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `roskilde_daycare`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roskilde_daycare`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roskilde_daycare`.`invoice` ;

CREATE TABLE IF NOT EXISTS `roskilde_daycare`.`invoice` (
  `invoice_id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL,
  `date_received` DATE NOT NULL,
  `date_sent` DATE NOT NULL,
  `from` VARCHAR(45) NOT NULL,
  `to` VARCHAR(45) NOT NULL,
  `parent_id` INT NULL,
  `teacher_id` INT NULL,
  PRIMARY KEY (`invoice_id`),
  INDEX `fk_invoice_teacher_idx` (`teacher_id` ASC) VISIBLE,
  INDEX `fk_invoice_parent_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `roskilde_daycare`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_parent`
    FOREIGN KEY (`parent_id`)
    REFERENCES `roskilde_daycare`.`parent` (`parent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
